= main-fns

image:https://img.shields.io/badge/License-MIT-yellow.svg[main-fns license, link=https://github.com/nabby27/main-fns/blob/main/LICENSE] image:https://img.shields.io/npm/v/main-fns.svg?style=flat&label=version[main-fns version, link=https://www.npmjs.com/package/main-fns] image:https://img.shields.io/github/workflow/status/nabby27/main-fns/Test/main?label=test[Status test, link=https://github.com/nabby27/main-fns/actions?query=workflow%3A%22Test%22] image:https://img.shields.io/codecov/c/github/nabby27/main-fns/main[Code coverage, link=https://codecov.io/gh/nabby27/main-fns/branch/main] image:https://badgen.net/bundlephobia/tree-shaking/main-fns/[Tree shaking] image:https://badgen.net/bundlephobia/minzip/main-fns[minzipped size] image:https://img.shields.io/npm/dw/main-fns[npm version] image:https://img.shields.io/badge/paypal-donate-yellow.svg[paypal, https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=M57SG9J5RQ6DJ&currency_code=EUR&source=url]

Javascript utility library created with TypeScript

== Documentation
Feel free to investigate the link:https://nabby27.github.io/main-fns/[main-fns documentation], it is structured by modules and created using JSDoc.

== Why main-fns?
It is quite tedious to be aware of all the dependencies and keep their changes. The idea of main-fns is that you only worry about this library. Main-fns will have all the main functions that are used in a common way such as the handling of dates, texts, arrays, numbers... Internally main-fns will use the best implementation of the moment and it will be updated for you.

== Installation

Using npm:
[source, shell]
----
npm i main-fns
----

== Some examples

[source, javascript]
----
import { addDays, camelCase, max } from 'main-fns'

addDays(1, new Date(1996, 5, 26)) // new Date(1996, 5, 27)

camelCase('hello world') // helloWorld

max(3, 4, 5, 2) // 5
----

== How to contribute?

See de link:https://github.com/nabby27/main-fns/blob/main/.github/CONTRIBUTING.adoc[CONTRIBUTING] page

== What changes does it have?

Detailed changes for each release are documented in the link:https://github.com/nabby27/main-fns/blob/main/CHANGELOG.adoc[CHANGELOG] page or in link:https://github.com/nabby27/main-fns/releases[release notes].

== License

See de link:https://github.com/nabby27/main-fns/blob/main/LICENSE[LICENSE] page